# Generated by Django 5.0.6 on 2024-05-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('NIM', models.CharField(max_length=15)),
                ('kelas', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_images/')),
            ],
        ),
    ]
